const SET_USER_PRICE = 'SET_USER_PRICE';
const SET_USER_SERVICE_NAME = 'SET_USER_SERVICE_NAME'
const ADD_ITEM_TO_LIST = 'ADD_ITEM_TO_LIST'
const SET_USER_CANCEL = 'SET_USER_CANCEL'
const EDIT_ITEM_LIST = 'EDIT_ITEM_LIST'
const SET_USER_ID  = 'SET_USER_ID'
const DELETE_ITEM_LIST = 'DELETE_ITEM_LIST'
const CURRENT_ID = 'CURRENT_ID'
const ADD_FILTER = 'ADD_FILTER'

export {
    SET_USER_PRICE,
    SET_USER_SERVICE_NAME,
    ADD_ITEM_TO_LIST,
    SET_USER_CANCEL,
    EDIT_ITEM_LIST,
    SET_USER_ID ,
    DELETE_ITEM_LIST,
    CURRENT_ID,
    ADD_FILTER
}
